Vagrant.configure("2") do |config|
  #
  # Descomentar si estamos destras de un proxy
  #
  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #  config.proxy.http     = "http://192.168.150.17:8080"
  #  config.proxy.https    = "http://192.168.150.17:8080"
  #  config.proxy.no_proxy = "localhost,127.0.0.1"
  #end

  config.vm.define "zbxsrv01" do |h|
    h.vm.box = "centos/8"
    h.vm.box_version = "1905.1"
    h.vm.hostname = "zbxsrv01"
    h.vm.network "private_network", ip: "10.0.100.100"
    h.vm.provision "shell", path: "provisioning.sh"
    h.vm.provider "libvirt" do |node|
      node.title = "zbxsrv01"
      node.memory = "2048"
      node.cpus = 2
    end    
  end
  config.vm.define "zbxclient01" do |h|
    h.vm.box = "centos/8"
    h.vm.box_version = "1905.1"
    h.vm.hostname = "zbxclient01"
    h.vm.network "private_network", ip: "10.0.100.101"
    h.vm.provision "shell", path: "provisioning.sh"
    h.vm.provider "libvirt" do |node|
      node.title = "zbxclient01"
      node.memory = "1024"
      node.cpus = 2
    end
  end
  config.vm.define "zbxclient02" do |h|
    h.vm.box = "centos/8"
    h.vm.box_version = "1905.1"
    h.vm.hostname = "zbxclient02"
    h.vm.network "private_network", ip: "10.0.100.102"
    h.vm.provision "shell", path: "provisioning.sh"
    h.vm.provider "libvirt" do |node|
      node.title = "zbxclient02"
      node.memory = "1024"
      node.cpus = 2
    end
  end
end
